version: "3"
services:
  db:
    container_name: mysqldb
    image: raviteja3929/dbimage
    ports:
      - "3306:3306"

  app:
    container_name: bankapp
    image: raviteja3929/appimage
    ports:
      - "1432:80"
    depends_on:
      - db
