version: "3"

services:
  db:
    container_name: mysqldb
    build: 
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "3306:3306"

  app:
    container_name: bankapp
    build: .
    ports:
      - "1432:80"
    depends_on:
      - db
