version: "3"

services:
  db:
    container_name: mysqldb
    image: raviteja3929/bloodbank:db
    ports:
      - "3306:3306"

  app:
    container_name: bankapp
    image: raviteja3929/bloodbank:app
    ports:
      - "1432:80"
    depends_on:
      - db
